version: '3'

networks:
  vk-network:
    driver: bridge

services:

        vk:
            container_name: vk
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            networks:
                - vk-network
            ports:
                - "9000:9000"
            volumes:
                - ./../vk:/vk:rw,cached
                - vk_log:/vk/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - maria-master

        nginx:
            container_name: nginx
            build:
                context: ./nginx
                args:
                    - timezone=${TZ}
            ports:
                - "81:80"
                - "443:443"
            networks:
                - vk-network
            depends_on:
                - vk
            volumes:
                - ./../vk/public:/vk/public
                - ./nginx/ssl:/etc/nginx/ssl
                - ./nginx/conf.d:/etc/nginx/conf.d
                - ./nginx/nginx_log:/var/log/nginx
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            env_file:
                - .env
            command: /bin/bash -c "exec nginx -g 'daemon off;'"

        redis:
            container_name: redis
            image: redis:latest
            ports:
                - "6379:6379"
            networks:
                - vk-network

        memcached:
            container_name: memcached
            image: memcached:latest
            ports:
                - "11211:11211"
            networks:
                - vk-network

        maria-master:
            container_name: maria_master
            image: mariadb:latest
            env_file:
                - ./db/master/.env.master
            ports:
                - "5406:3306"
            volumes:
                - ./db/master/master.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/master/mysql.master.cnf:/etc/mysql/conf.d/mysql.master.cnf
                - ./db/master/.data/mysql:/var/lib/mysql:rw
            networks:
                - vk-network

        maria-slave-1:
            container_name: maria_slave_1
            image: mariadb:latest
            env_file:
                - ./db/slaves/email/.env.slave
            ports:
                - "5407:3306"
            volumes:
                - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/slaves/email/mysql.slave.cnf:/etc/mysql/conf.d/mysql.slave.cnf
                - ./db/slaves/email/.data/mysql:/var/lib/mysql:rw
            networks:
                - vk-network
                
        maria-slave-2:
            container_name: maria_slave_2
            image: mariadb:latest
            env_file:
                - ./db/slaves/sms/.env.slave
            ports:
                - "5408:3306"
            volumes:
                - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/slaves/sms/mysql.slave.cnf:/etc/mysql/conf.d/mysql.slave.cnf
                - ./db/slaves/sms/.data/mysql:/var/lib/mysql:rw
            networks:
                - vk-network
                                
        maria-slave-3:
            container_name: maria_slave_3
            image: mariadb:latest
            env_file:
                - ./db/slaves/sms/.env.slave
            ports:
                - "5409:3306"
            volumes:
                - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/slaves/slave-3/mysql.slave.cnf:/etc/mysql/conf.d/mysql.slave.cnf
                - ./db/slaves/slave-3/.data/mysql:/var/lib/mysql:rw
            networks:
                - vk-network
                                
        maria-slave-4:
            container_name: maria_slave_4
            image: mariadb:latest
            env_file:
                - ./db/slaves/sms/.env.slave
            ports:
                - "5410:3306"
            volumes:
                - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/slaves/slave-4/mysql.slave.cnf:/etc/mysql/conf.d/mysql.slave.cnf
                - ./db/slaves/slave-4/.data/mysql:/var/lib/mysql:rw
            networks:
                - vk-network

volumes:
    nginx_log:
    vk_log:
    db:
        driver: local